### ISSUE TITLE
Ask-tell mode capability

### ISSUE THREAD

**Issue by lancekavalsky** [PV-Lab/ZoMBI#1]
I'm not sure if I'm just missing it, but does the code currently support operating in an ask-tell mode (e.g. something akin to [dragonfly](https://dragonfly-opt.readthedocs.io/en/master/getting_started_ask_tell/) or [olympus](https://aspuru-guzik-group.github.io/olympus/examples/notebooks/planners_interface.html#Ask-and-Tell))? 

If not, is this something on your radar? Would be super helpful for applying ZoMBI on-the-fly

This is amazing work, thanks for open-sourcing!

**Comment by buonassisi** [comment]
Hi Lance,Thanks for your question. We’re currently discussing a continuation project that would add more features, including potentially the ones you indicate here. If you have any other requests, please send them to us directly, and will make sure to include them in our discussions. :o)Best,Tonio--Tonio BuonassisiProf. Mech. Eng., MIT✉️ ***@***.***💻 http://www.buonassisigroup.com🤝 https://www.LinkedIn.com/today/author/tonio-buonassisi-7854543On Oct 24, 2023, at 12:36, Lance Kavalsky ***@***.***> wrote:﻿
I'm not sure if I'm just missing it, but does the code currently support operating in an ask-tell mode (e.g. something akin to dragonfly or olympus)?
If not, is this something on your radar? Would be super helpful for applying ZoMBI on-the-fly
This is amazing work, thanks for open-sourcing!

**Comment by aleks-py** [comment]
Lance, this is not implemented explicitly into this iteration of ZoMBI, however, it is very simple to add your own measurements to ZoMBI, emulating the "tell" command. 

In **zombi.py**, within the 'activate_zombi()' definition on line 96, replace 'fX_bounded' with your numerical measurement that you want to reveal to the algorithm, where 'X_new = X_bounded' on line 95 represents "ask". That's it!

We have created the ZoMBI architecture to eventually pair directly with experimentation where we will be using an "ask" and "tell"-adjacent framework. So keep up to date with our new repo that will be linked directly to an experimentation pipeline: https://github.com/PV-Lab/ZoMBI-Hop/tree/main
